export const ROUTES = {
  HOME: "/",
  PRODUCT: `/products`,
  CHECKOUT: "/checkout",
  CONTACT: "/contact-us",
  TERMS: "/terms",
  POLICY: "/privacy",
  FAQ: "/faq",
  FORGET_PASSWORD: "/forget-password",
  ACCOUNT: "/account",
  ORDERS: "/account/orders",
  CHANGE_PASSWORD: "/account/change-password",
  SHOP: "/shop",
  LOGIN: "/signin",
  SIGN_UP: "/signup",
  SEARCH: "/search",
  COLLECTIONS: "/collections",
  CATEGORY: "/category",
  ORDER: "/order",
};
